services:
  # Backend (Flask)
  - type: web
    name: rei-backend
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      # Stelle sicher, dass gunicorn da ist
      python -c "import pkgutil, sys; sys.exit(0 if pkgutil.find_loader('gunicorn') else 1)" || pip install gunicorn
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT src.main:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"

  # Frontend (Vite/React) als Static Site (kein plan!)
  - type: web
    name: rei-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      # Frontend bekommt die Backend-URL automatisch
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: rei-backend
          property: url
    # SPA-Fallback für Client-Routing
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
