services:
  # Backend (Flask)
  - type: web
    name: rei-backend
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: bash -lc 'mkdir -p src/database && exec gunicorn -w 2 -k gthread -b 0.0.0.0:$PORT src.main:app'
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
    # SQLite persistent machen
    disk:
      name: rei-db
      mountPath: /opt/render/project/src/backend/src/database
      sizeGB: 1
    healthCheckPath: /health

  # Frontend (Vite/React) als Static Site
  - type: web
    name: rei-frontend
    runtime: static
    plan: free
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    # API-URL automatisch vom Backend beziehen (öffentliche URL)
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          name: rei-backend
          type: web
          envVarKey: RENDER_EXTERNAL_URL
    # SPA-Fallback für Client-Routing
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
