services:
  - type: web
    name: rei-backend
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      pip install gunicorn
    # Für SQLite: genau 1 Worker
    startCommand: gunicorn -w 1 -b 0.0.0.0:$PORT src.main:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      # sorgt dafür, dass die SQLite-Datei sicher geschrieben werden kann
      - key: DATA_DIR
        value: "/tmp"
