services:
  - type: web
    name: backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: ENV
        value: production
    autoDeploy: true
    rootDir: backend
    healthCheckPath: /health

  - type: static
    name: frontend
    plan: free
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: backend
          property: host
    pullRequestPreviewsEnabled: true
