services:
  - type: web
    name: rei-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: bash -lc 'mkdir -p src/database && exec gunicorn -w 2 -k gthread -b 0.0.0.0:$PORT src.main:app'
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    # Persistente Files für SQLite
    disk:
      name: rei-db
      mountPath: /opt/render/project/src/backend/src/database
      sizeGB: 1
    healthCheckPath: /health

  - type: static
    name: rei-frontend
    plan: free
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    # Frontend bekommt die Backend-URL automatisch als Env-Var
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: rei-backend
          property: url
    # SPA-Fallback
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
